In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sp

In [2]:
xop = sp.bsr_matrix([[0, 1], [1, 0]])
yop = sp.bsr_matrix([[0, -1j], [1j, 0]])
zop = sp.bsr_matrix([[1, 0], [0, -1]])

In [265]:
print(np.round(sp.kron(yop, sp.kron(zop, xop)) - sp.kron(xop, sp.kron(zop, yop)), decimals=1).todense())

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.-2.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+2.j 0.+0.j]
 [0.+0.j 0.+2.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-2.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [270]:
sp.kron(xop, sp.kron(yop, xop)).todense() - sp.kron(sp.identity(2), sp.kron(yop, sp.identity(2)))

matrix([[0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j],
        [0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j],
        [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.+0.j]])

In [248]:
ns = 4
nq = 2 * ns
xops = []
yops = []
zops = []
for i in range(nq):
    id1 = sp.identity(2 ** i)
    id2 = sp.identity(2 ** (nq - i - 1))
    xops.append(sp.kron(id1, sp.kron(xop, id2)))
    yops.append(sp.kron(id1, sp.kron(yop, id2)))
    zops.append(sp.kron(id1, sp.kron(zop, id2)))

xops_r = []
yops_r = []
zops_r = []
for i in range(ns):
    id1 = sp.identity(2 ** i)
    id2 = sp.identity(2 ** (ns - i - 1))
    xops_r.append(sp.kron(id1, sp.kron(xop, id2)))
    yops_r.append(sp.kron(id1, sp.kron(yop, id2)))
    zops_r.append(sp.kron(id1, sp.kron(zop, id2)))
    
parity_conj = sp.identity(2 ** ns)
for i in range(ns // 2):
    op = xops_r[i] @ xops_r[-i - 1]
    op += yops_r[i] @ yops_r[-i - 1]
    op += sp.identity(2 ** ns)
    op += zops_r[i] @ zops_r[-i - 1]
    op /= 2
    parity_conj = parity_conj @ op
    
    
charge_conj = sp.identity(2 ** ns)
for i in range(ns - 1):
    op = xops_r[i] @ xops_r[i + 1]
    op += yops_r[i] @ yops_r[i + 1]
    op += sp.identity(2 ** ns)
    op += zops_r[i] @ zops_r[i + 1]
    op /= 2
    charge_conj = charge_conj @ op
    print(np.linalg.eigh(charge_conj.todense())[0])

[-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[-1.41421356e+00 -1.41421356e+00 -1.00000000e+00 -1.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.04083409e-17
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.41421356e+00  1.41421356e+00]
[-1.61803399e+00 -1.41421356e+00 -1.00000000e+00 -1.00000000e+00
 -6.18033989e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.04083409e-17  6.18033989e-01  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.41421356e+00  1.61803399e+00]


In [249]:
h_fh = 0
h_g = 0
h_m = 0
for i in range(ns):
    h_g += 1 / 2 * xops[2 * i + 1]
    h_m += 1 / 2 * (-1) ** i * zops[2 * i]
for i in range(ns - 1):
    h_fh += 1 / 4 * (xops[2 * i] @ xops[2 * i + 2] + yops[2 * i] @ yops[2 * i + 2]) @ zops[2 * i + 1]
term = 1 / 4 * (xops[0] @ xops[-2] + yops[0] @ yops[-2]) @ zops[-1] @ xops[1] @ xops[-3]
h_fh += term
gauss_ops = [xops[-1] @ zops[0] @ xops[1], xops[1] @ -zops[2] @ xops[3],
             xops[3] @ zops[4] @ xops[5], -xops[5] @ zops[6] @ xops[7]]
# for i in range(ns):
#     oper = (-1) ** i * xops[(2 * i - 1) % nq] @ zops[2 * i] @ xops[(2 * i + 1) % nq]
#     gauss_ops.append(oper.todense())
h_fh2 = 0
h_g2 = 0
h_m2 = 0
for i in range(ns):
    h_fh2 += 1 / 4 * (xops_r[i] @ xops_r[(i + 2) % ns] + sp.identity(2 ** ns)) @ zops_r[(i + 1) % ns] 
    h_g2 += 1 / 2 * xops_r[i]
    h_m2 += 1 / 2 * xops_r[i] @ xops_r[(i + 1) % ns]

In [250]:
(ham_s @ charge_conj - charge_conj @ ham_s).todense()

matrix([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
         0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0

In [256]:
ham_g = h_fh + h_g - h_m
ham_s = h_fh2 + h_g2 - h_m2
sign = -1
ham_sp = 0.25 * (sp.identity(16) + sign * parity_conj) @ ham_s @ (sp.identity(16) + sign * parity_conj)

In [257]:
ham_g = ham_g.todense()
ham_sp = ham_sp.todense()

In [258]:
eigsys_g = np.linalg.eigh(ham_g)
eigsys_s = np.linalg.eigh(ham_sp)
eigsys_s_f = np.linalg.eigh(ham_s.todense())

allowed = []
a_vecs = []
for i in range(2 ** nq):
    vec = 0 + eigsys_g[1][:, i]
    flag = True
    for j in range(ns):
        vec = 0.5 * (np.identity(2 ** nq) + gauss_ops[j]) @ vec
        norm = np.sqrt(vec.conjugate().transpose() @ vec)
        if norm < 0.00000001:
            flag = False
            break
        else:
            vec /= norm
    if flag:
        a_vecs.append(vec)
        okay = True
        for j in range(len(a_vecs) - 1):
            if vec.conjugate().transpose() @ a_vecs[j] > 0.99:
                okay = False
                break
        if okay:
#         print(i, np.where(np.abs(np.round(vec.conjugate().transpose() @ eigsys_g[1], decimals=5)) == 1))
            allowed.append(eigsys_g[0][i])
print(len(allowed))

In [259]:
eigsys_s[0], eigsys_s_f[0]

(array([-1.17008649e+00, -1.00000000e+00, -2.38613590e-16, -2.09826124e-16,
        -3.61662491e-17, -3.30367127e-17, -6.16297582e-33,  0.00000000e+00,
         0.00000000e+00,  9.06528118e-18,  5.48388640e-17,  6.87811446e-17,
         2.22044111e-16,  6.88892183e-01,  1.00000000e+00,  2.48119430e+00]),
 array([-4.30967645e+00, -1.17008649e+00, -1.00000000e+00, -1.00000000e+00,
        -8.98586769e-01, -6.32491781e-01, -6.26743849e-16, -1.39096231e-16,
        -3.13491870e-17,  7.55443008e-17,  6.88892183e-01,  1.00000000e+00,
         1.00000000e+00,  1.27096030e+00,  2.48119430e+00,  2.56979469e+00]))

In [255]:
for i in range(16):
    vector = eigsys_s[1][:, i]
    print(np.round(vector.conjugate().transpose() @ charge_conj @ vector, decimals=4))

[[1.+0.j]]
[[-0.+0.j]]
[[1.+0.j]]
[[1.+0.j]]
[[0.2794+0.j]]
[[-0.5704+0.j]]
[[-0.5509+0.j]]
[[-0.5385+0.j]]
[[-0.5803+0.j]]
[[-0.203+0.j]]
[[-0.4453+0.j]]
[[-0.219+0.j]]
[[-0.172+0.j]]
[[0.+0.j]]
[[1.+0.j]]
[[1.+0.j]]


In [162]:
op = (sp.identity(4) + sp.kron(zop, zop) + sp.kron(xop, xop) + sp.kron(yop, yop)).todense() / 2

In [123]:
np.linalg.eigh(op)

(array([-1.,  1.,  1.,  1.]),
 matrix([[ 0.        +0.j,  0.        +0.j,  1.        +0.j,
           0.        +0.j],
         [-0.70710678+0.j,  0.70710678+0.j,  0.        +0.j,
           0.        +0.j],
         [ 0.70710678+0.j,  0.70710678+0.j,  0.        +0.j,
           0.        +0.j],
         [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
           1.        +0.j]]))

In [139]:
np.linalg.eigh(charge_conj.todense())

(array([-1.61803399e+00, -1.41421356e+00, -1.00000000e+00, -1.00000000e+00,
        -6.18033989e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.04083409e-17,  6.18033989e-01,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  1.41421356e+00,  1.61803399e+00]),
 matrix([[ 0.00000000e+00+0.j,  0.00000000e+00+0.j, -0.00000000e+00+0.j,
          -0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
           0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
           0.00000000e+00+0.j,  1.00000000e+00+0.j,  0.00000000e+00+0.j,
           0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
           0.00000000e+00+0.j],
         [ 0.00000000e+00+0.j,  0.00000000e+00+0.j, -7.07106781e-01+0.j,
          -0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
           0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
           0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,
     